# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PowerDNS-Backend-MySQL
version:      0.05
version_from: lib/PowerDNS/Backend/MySQL.pm
installdirs:  site
requires:
    DBI:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
